### ISSUE TITLE
How do I use the Poisson reconstruction feature in the PCL library?

### ISSUE THREAD

**Issue by mosaicchen** [S1ink/UE5-LidarSim#2]
Hello, it's great to see your sharing about this project. I am currently researching how to convert point cloud data in Unreal into mesh. Can you give me some advice? I know that I can use the Poisson reconstruction feature in the PCL library, but when I tried to add this feature to my script, the Visual Studio compilation failed.

**Comment by S1ink** [comment]
Personally I have never used that part of PCL so cannot verify that it is working in the project or even was compiled correctly. Are you using the included PCL build (from releases) or your own build/install? Also what exactly is failing for the build (could you include the output log)?

Another thing to note is that even if you do get it to build, it will be difficult to use the UE data in any PCL functions. For the code I have written for this project already, I had to deal with a lot of mismatched memory allocations/deallocations when passing in buffers generated by UE. I'm pretty sure that this is because UE uses a special allocation method that differs from what PCL was compiled with, thus when the PCL functions try to resize any arrays, they fail. Practically this means either avoiding or rewriting all PCL functionally that tries to resize or store references to external data (this is what I did for most of the functions I use from PCL).

Sorry to make it sound like a such lost cause - hopefully it isn't actually this bad!

**Comment by mosaicchen** [comment]
Yes, I used the included PCL build (from releases), and the most common issue I encountered was missing script files/references errors(I think that some of the include file do not exist in the 'from releases' build.). 

As you mentioned, it's quite difficult to directly use PCL methods within UE. After much discussion with my partner, we concluded that writing an external program to communicate data with UE is an easier approach to implement. This way, we can more easily utilize these functionalities, whether it's using the PCL library or other 3D computation libraries.

Thank you for your support!
